window.josaaData = [
  { year: 2016, iit: "IIT Bombay", branch: "Computer Science and Engineering", seats: 110, openingRank: 1, closingRank: 63 },
  { year: 2016, iit: "IIT Bombay", branch: "Electrical Engineering", seats: 120, openingRank: 40, closingRank: 320 },
  { year: 2016, iit: "IIT Bombay", branch: "Mechanical Engineering", seats: 118, openingRank: 110, closingRank: 780 },
  { year: 2016, iit: "IIT Bombay", branch: "Mathematics and Computing", seats: 70, openingRank: 18, closingRank: 170 },
  { year: 2016, iit: "IIT Delhi", branch: "Computer Science and Engineering", seats: 120, openingRank: 2, closingRank: 105 },
  { year: 2016, iit: "IIT Delhi", branch: "Electrical Engineering", seats: 115, openingRank: 70, closingRank: 390 },
  { year: 2016, iit: "IIT Delhi", branch: "Mechanical Engineering", seats: 112, openingRank: 150, closingRank: 930 },
  { year: 2016, iit: "IIT Delhi", branch: "Mathematics and Computing", seats: 80, openingRank: 30, closingRank: 220 },
  { year: 2016, iit: "IIT Madras", branch: "Computer Science and Engineering", seats: 100, openingRank: 9, closingRank: 155 },
  { year: 2016, iit: "IIT Madras", branch: "Electrical Engineering", seats: 95, openingRank: 120, closingRank: 420 },
  { year: 2016, iit: "IIT Madras", branch: "Mechanical Engineering", seats: 106, openingRank: 240, closingRank: 1120 },
  { year: 2016, iit: "IIT Kanpur", branch: "Computer Science and Engineering", seats: 92, openingRank: 15, closingRank: 210 },
  { year: 2016, iit: "IIT Kanpur", branch: "Electrical Engineering", seats: 97, openingRank: 130, closingRank: 470 },
  { year: 2016, iit: "IIT Kanpur", branch: "Mechanical Engineering", seats: 100, openingRank: 320, closingRank: 980 },
  { year: 2016, iit: "IIT Guwahati", branch: "Computer Science and Engineering", seats: 85, openingRank: 55, closingRank: 610 },
  { year: 2016, iit: "IIT Guwahati", branch: "Electronics and Electrical Engineering", seats: 90, openingRank: 230, closingRank: 1050 },
  { year: 2016, iit: "IIT Kharagpur", branch: "Aerospace Engineering", seats: 75, openingRank: 450, closingRank: 1800 },
  { year: 2016, iit: "IIT Roorkee", branch: "Civil Engineering", seats: 100, openingRank: 520, closingRank: 2300 },

  { year: 2017, iit: "IIT Bombay", branch: "Computer Science and Engineering", seats: 115, openingRank: 1, closingRank: 60 },
  { year: 2017, iit: "IIT Bombay", branch: "Electrical Engineering", seats: 122, openingRank: 42, closingRank: 300 },
  { year: 2017, iit: "IIT Bombay", branch: "Mechanical Engineering", seats: 119, openingRank: 105, closingRank: 760 },
  { year: 2017, iit: "IIT Bombay", branch: "Mathematics and Computing", seats: 74, openingRank: 16, closingRank: 165 },
  { year: 2017, iit: "IIT Delhi", branch: "Computer Science and Engineering", seats: 122, openingRank: 2, closingRank: 100 },
  { year: 2017, iit: "IIT Delhi", branch: "Electrical Engineering", seats: 116, openingRank: 68, closingRank: 375 },
  { year: 2017, iit: "IIT Delhi", branch: "Mechanical Engineering", seats: 113, openingRank: 145, closingRank: 910 },
  { year: 2017, iit: "IIT Delhi", branch: "Mathematics and Computing", seats: 85, openingRank: 25, closingRank: 210 },
  { year: 2017, iit: "IIT Madras", branch: "Computer Science and Engineering", seats: 102, openingRank: 10, closingRank: 150 },
  { year: 2017, iit: "IIT Madras", branch: "Electrical Engineering", seats: 96, openingRank: 118, closingRank: 410 },
  { year: 2017, iit: "IIT Madras", branch: "Mechanical Engineering", seats: 108, openingRank: 235, closingRank: 1100 },
  { year: 2017, iit: "IIT Kanpur", branch: "Computer Science and Engineering", seats: 93, openingRank: 16, closingRank: 205 },
  { year: 2017, iit: "IIT Kanpur", branch: "Electrical Engineering", seats: 98, openingRank: 128, closingRank: 455 },
  { year: 2017, iit: "IIT Kanpur", branch: "Mechanical Engineering", seats: 101, openingRank: 315, closingRank: 960 },
  { year: 2017, iit: "IIT Guwahati", branch: "Computer Science and Engineering", seats: 87, openingRank: 52, closingRank: 590 },
  { year: 2017, iit: "IIT Guwahati", branch: "Electronics and Electrical Engineering", seats: 91, openingRank: 225, closingRank: 1020 },
  { year: 2017, iit: "IIT Kharagpur", branch: "Aerospace Engineering", seats: 76, openingRank: 430, closingRank: 1750 },
  { year: 2017, iit: "IIT Roorkee", branch: "Civil Engineering", seats: 102, openingRank: 500, closingRank: 2250 },

  { year: 2018, iit: "IIT Bombay", branch: "Computer Science and Engineering", seats: 118, openingRank: 1, closingRank: 58 },
  { year: 2018, iit: "IIT Bombay", branch: "Electrical Engineering", seats: 130, openingRank: 70, closingRank: 430 },
  { year: 2018, iit: "IIT Bombay", branch: "Mechanical Engineering", seats: 120, openingRank: 108, closingRank: 740 },
  { year: 2018, iit: "IIT Bombay", branch: "Mathematics and Computing", seats: 78, openingRank: 15, closingRank: 150 },
  { year: 2018, iit: "IIT Delhi", branch: "Computer Science and Engineering", seats: 124, openingRank: 2, closingRank: 96 },
  { year: 2018, iit: "IIT Delhi", branch: "Electrical Engineering", seats: 117, openingRank: 65, closingRank: 360 },
  { year: 2018, iit: "IIT Delhi", branch: "Mechanical Engineering", seats: 114, openingRank: 138, closingRank: 880 },
  { year: 2018, iit: "IIT Delhi", branch: "Mathematics and Computing", seats: 88, openingRank: 22, closingRank: 195 },
  { year: 2018, iit: "IIT Madras", branch: "Computer Science and Engineering", seats: 105, openingRank: 10, closingRank: 160 },
  { year: 2018, iit: "IIT Madras", branch: "Electrical Engineering", seats: 98, openingRank: 110, closingRank: 395 },
  { year: 2018, iit: "IIT Madras", branch: "Mechanical Engineering", seats: 110, openingRank: 230, closingRank: 1080 },
  { year: 2018, iit: "IIT Kanpur", branch: "Computer Science and Engineering", seats: 95, openingRank: 14, closingRank: 198 },
  { year: 2018, iit: "IIT Kanpur", branch: "Electrical Engineering", seats: 100, openingRank: 122, closingRank: 440 },
  { year: 2018, iit: "IIT Kanpur", branch: "Mechanical Engineering", seats: 102, openingRank: 300, closingRank: 930 },
  { year: 2018, iit: "IIT Guwahati", branch: "Computer Science and Engineering", seats: 89, openingRank: 48, closingRank: 565 },
  { year: 2018, iit: "IIT Guwahati", branch: "Electronics and Electrical Engineering", seats: 92, openingRank: 218, closingRank: 1005 },
  { year: 2018, iit: "IIT Kharagpur", branch: "Aerospace Engineering", seats: 78, openingRank: 420, closingRank: 1680 },
  { year: 2018, iit: "IIT Roorkee", branch: "Civil Engineering", seats: 103, openingRank: 490, closingRank: 2200 },

  { year: 2019, iit: "IIT Bombay", branch: "Computer Science and Engineering", seats: 120, openingRank: 1, closingRank: 57 },
  { year: 2019, iit: "IIT Bombay", branch: "Electrical Engineering", seats: 132, openingRank: 68, closingRank: 410 },
  { year: 2019, iit: "IIT Bombay", branch: "Mechanical Engineering", seats: 122, openingRank: 105, closingRank: 710 },
  { year: 2019, iit: "IIT Bombay", branch: "Mathematics and Computing", seats: 82, openingRank: 14, closingRank: 145 },
  { year: 2019, iit: "IIT Delhi", branch: "Computer Science and Engineering", seats: 125, openingRank: 2, closingRank: 92 },
  { year: 2019, iit: "IIT Delhi", branch: "Electrical Engineering", seats: 118, openingRank: 63, closingRank: 350 },
  { year: 2019, iit: "IIT Delhi", branch: "Mechanical Engineering", seats: 115, openingRank: 132, closingRank: 850 },
  { year: 2019, iit: "IIT Delhi", branch: "Mathematics and Computing", seats: 90, openingRank: 20, closingRank: 185 },
  { year: 2019, iit: "IIT Madras", branch: "Computer Science and Engineering", seats: 107, openingRank: 9, closingRank: 150 },
  { year: 2019, iit: "IIT Madras", branch: "Electrical Engineering", seats: 100, openingRank: 105, closingRank: 385 },
  { year: 2019, iit: "IIT Madras", branch: "Mechanical Engineering", seats: 112, openingRank: 220, closingRank: 1040 },
  { year: 2019, iit: "IIT Kanpur", branch: "Computer Science and Engineering", seats: 97, openingRank: 13, closingRank: 192 },
  { year: 2019, iit: "IIT Kanpur", branch: "Electrical Engineering", seats: 102, openingRank: 116, closingRank: 428 },
  { year: 2019, iit: "IIT Kanpur", branch: "Mechanical Engineering", seats: 103, openingRank: 290, closingRank: 900 },
  { year: 2019, iit: "IIT Guwahati", branch: "Computer Science and Engineering", seats: 90, openingRank: 45, closingRank: 550 },
  { year: 2019, iit: "IIT Guwahati", branch: "Data Science and Artificial Intelligence", seats: 60, openingRank: 150, closingRank: 620 },
  { year: 2019, iit: "IIT Guwahati", branch: "Electronics and Electrical Engineering", seats: 94, openingRank: 215, closingRank: 995 },
  { year: 2019, iit: "IIT Hyderabad", branch: "Artificial Intelligence", seats: 55, openingRank: 120, closingRank: 590 },
  { year: 2019, iit: "IIT Kharagpur", branch: "Aerospace Engineering", seats: 80, openingRank: 405, closingRank: 1620 },
  { year: 2019, iit: "IIT Roorkee", branch: "Civil Engineering", seats: 90, openingRank: 500, closingRank: 2200 },

  { year: 2020, iit: "IIT Bombay", branch: "Computer Science and Engineering", seats: 122, openingRank: 1, closingRank: 56 },
  { year: 2020, iit: "IIT Bombay", branch: "Electrical Engineering", seats: 134, openingRank: 65, closingRank: 398 },
  { year: 2020, iit: "IIT Bombay", branch: "Mechanical Engineering", seats: 123, openingRank: 102, closingRank: 695 },
  { year: 2020, iit: "IIT Bombay", branch: "Mathematics and Computing", seats: 90, openingRank: 35, closingRank: 270 },
  { year: 2020, iit: "IIT Delhi", branch: "Computer Science and Engineering", seats: 127, openingRank: 2, closingRank: 89 },
  { year: 2020, iit: "IIT Delhi", branch: "Electrical Engineering", seats: 120, openingRank: 60, closingRank: 338 },
  { year: 2020, iit: "IIT Delhi", branch: "Mechanical Engineering", seats: 116, openingRank: 130, closingRank: 830 },
  { year: 2020, iit: "IIT Delhi", branch: "Mathematics and Computing", seats: 92, openingRank: 18, closingRank: 175 },
  { year: 2020, iit: "IIT Madras", branch: "Computer Science and Engineering", seats: 108, openingRank: 8, closingRank: 145 },
  { year: 2020, iit: "IIT Madras", branch: "Electrical Engineering", seats: 101, openingRank: 100, closingRank: 378 },
  { year: 2020, iit: "IIT Madras", branch: "Mechanical Engineering", seats: 113, openingRank: 215, closingRank: 1010 },
  { year: 2020, iit: "IIT Kanpur", branch: "Computer Science and Engineering", seats: 98, openingRank: 12, closingRank: 186 },
  { year: 2020, iit: "IIT Kanpur", branch: "Electrical Engineering", seats: 100, openingRank: 100, closingRank: 510 },
  { year: 2020, iit: "IIT Kanpur", branch: "Mechanical Engineering", seats: 104, openingRank: 280, closingRank: 875 },
  { year: 2020, iit: "IIT Guwahati", branch: "Computer Science and Engineering", seats: 92, openingRank: 44, closingRank: 545 },
  { year: 2020, iit: "IIT Guwahati", branch: "Data Science and Artificial Intelligence", seats: 65, openingRank: 135, closingRank: 600 },
  { year: 2020, iit: "IIT Guwahati", branch: "Electronics and Electrical Engineering", seats: 95, openingRank: 210, closingRank: 980 },
  { year: 2020, iit: "IIT Hyderabad", branch: "Artificial Intelligence", seats: 65, openingRank: 95, closingRank: 540 },
  { year: 2020, iit: "IIT Kharagpur", branch: "Aerospace Engineering", seats: 82, openingRank: 390, closingRank: 1550 },
  { year: 2020, iit: "IIT Roorkee", branch: "Civil Engineering", seats: 92, openingRank: 485, closingRank: 2150 },

  { year: 2021, iit: "IIT Bombay", branch: "Computer Science and Engineering", seats: 124, openingRank: 1, closingRank: 55 },
  { year: 2021, iit: "IIT Bombay", branch: "Electrical Engineering", seats: 136, openingRank: 63, closingRank: 386 },
  { year: 2021, iit: "IIT Bombay", branch: "Mechanical Engineering", seats: 124, openingRank: 99, closingRank: 680 },
  { year: 2021, iit: "IIT Bombay", branch: "Mathematics and Computing", seats: 92, openingRank: 13, closingRank: 138 },
  { year: 2021, iit: "IIT Delhi", branch: "Computer Science and Engineering", seats: 128, openingRank: 2, closingRank: 87 },
  { year: 2021, iit: "IIT Delhi", branch: "Electrical Engineering", seats: 110, openingRank: 85, closingRank: 470 },
  { year: 2021, iit: "IIT Delhi", branch: "Mechanical Engineering", seats: 117, openingRank: 125, closingRank: 810 },
  { year: 2021, iit: "IIT Delhi", branch: "Mathematics and Computing", seats: 94, openingRank: 17, closingRank: 168 },
  { year: 2021, iit: "IIT Madras", branch: "Computer Science and Engineering", seats: 110, openingRank: 8, closingRank: 140 },
  { year: 2021, iit: "IIT Madras", branch: "Electrical Engineering", seats: 102, openingRank: 96, closingRank: 365 },
  { year: 2021, iit: "IIT Madras", branch: "Mechanical Engineering", seats: 100, openingRank: 310, closingRank: 1200 },
  { year: 2021, iit: "IIT Kanpur", branch: "Computer Science and Engineering", seats: 99, openingRank: 11, closingRank: 180 },
  { year: 2021, iit: "IIT Kanpur", branch: "Electrical Engineering", seats: 103, openingRank: 95, closingRank: 400 },
  { year: 2021, iit: "IIT Kanpur", branch: "Mechanical Engineering", seats: 105, openingRank: 270, closingRank: 850 },
  { year: 2021, iit: "IIT Guwahati", branch: "Computer Science and Engineering", seats: 95, openingRank: 40, closingRank: 530 },
  { year: 2021, iit: "IIT Guwahati", branch: "Data Science and Artificial Intelligence", seats: 72, openingRank: 120, closingRank: 560 },
  { year: 2021, iit: "IIT Guwahati", branch: "Electronics and Electrical Engineering", seats: 96, openingRank: 208, closingRank: 970 },
  { year: 2021, iit: "IIT Hyderabad", branch: "Artificial Intelligence", seats: 70, openingRank: 90, closingRank: 520 },
  { year: 2021, iit: "IIT Kharagpur", branch: "Aerospace Engineering", seats: 84, openingRank: 380, closingRank: 1490 },
  { year: 2021, iit: "IIT Roorkee", branch: "Civil Engineering", seats: 93, openingRank: 470, closingRank: 2100 },

  { year: 2022, iit: "IIT Bombay", branch: "Computer Science and Engineering", seats: 120, openingRank: 1, closingRank: 61 },
  { year: 2022, iit: "IIT Bombay", branch: "Electrical Engineering", seats: 138, openingRank: 60, closingRank: 375 },
  { year: 2022, iit: "IIT Bombay", branch: "Mechanical Engineering", seats: 126, openingRank: 96, closingRank: 665 },
  { year: 2022, iit: "IIT Bombay", branch: "Mathematics and Computing", seats: 95, openingRank: 12, closingRank: 132 },
  { year: 2022, iit: "IIT Delhi", branch: "Computer Science and Engineering", seats: 130, openingRank: 2, closingRank: 100 },
  { year: 2022, iit: "IIT Delhi", branch: "Electrical Engineering", seats: 121, openingRank: 58, closingRank: 330 },
  { year: 2022, iit: "IIT Delhi", branch: "Mechanical Engineering", seats: 118, openingRank: 120, closingRank: 790 },
  { year: 2022, iit: "IIT Delhi", branch: "Mathematics and Computing", seats: 96, openingRank: 16, closingRank: 160 },
  { year: 2022, iit: "IIT Madras", branch: "Computer Science and Engineering", seats: 112, openingRank: 7, closingRank: 136 },
  { year: 2022, iit: "IIT Madras", branch: "Electrical Engineering", seats: 104, openingRank: 92, closingRank: 352 },
  { year: 2022, iit: "IIT Madras", branch: "Mechanical Engineering", seats: 114, openingRank: 205, closingRank: 980 },
  { year: 2022, iit: "IIT Kanpur", branch: "Computer Science and Engineering", seats: 100, openingRank: 10, closingRank: 175 },
  { year: 2022, iit: "IIT Kanpur", branch: "Electrical Engineering", seats: 104, openingRank: 90, closingRank: 392 },
  { year: 2022, iit: "IIT Kanpur", branch: "Mechanical Engineering", seats: 106, openingRank: 260, closingRank: 820 },
  { year: 2022, iit: "IIT Guwahati", branch: "Computer Science and Engineering", seats: 97, openingRank: 38, closingRank: 505 },
  { year: 2022, iit: "IIT Guwahati", branch: "Data Science and Artificial Intelligence", seats: 78, openingRank: 110, closingRank: 520 },
  { year: 2022, iit: "IIT Guwahati", branch: "Electronics and Electrical Engineering", seats: 85, openingRank: 220, closingRank: 980 },
  { year: 2022, iit: "IIT Hyderabad", branch: "Artificial Intelligence", seats: 75, openingRank: 80, closingRank: 500 },
  { year: 2022, iit: "IIT Kharagpur", branch: "Aerospace Engineering", seats: 85, openingRank: 370, closingRank: 1450 },
  { year: 2022, iit: "IIT Roorkee", branch: "Civil Engineering", seats: 95, openingRank: 455, closingRank: 2050 }
];